### ISSUE TITLE
is acess token from the examples literally the one we should all use ?

### ISSUE THREAD

**Issue by alex-drocks** [xr0master/gmail-nodemailer-transport#5]
Sorry I'm so far from understanding all that oauth2 involves that I can't even tell if your examples are giving out a real access token or if we need to handle that part with Google?

Thanks in advance

**Comment by xr0master** [comment]
Hey. No, this is just example. The real access token is much longer :)

**Comment by xr0master** [comment]
BTW you can play with oauth2 (select Gmail)
https://developers.google.com/oauthplayground/
