### ISSUE TITLE
A few questions on oauth scope

### ISSUE THREAD

**Issue by Zonalds** [xr0master/gmail-nodemailer-transport#6]
Hey,

Thank you for making this, you have no idea how helpful it is; thank you.

I have a couple of questions:

- What scopes do we need to ask the google for? 
-  Any recommendation on a react/nextjs oauth library to fetch the access and refresh token?

**Comment by xr0master** [comment]
Hey, thanks.
1. You need only the send scope to send emails: https://www.googleapis.com/auth/gmail.send
2. I don't know, we are using our custom implementation.
